export { Home } from "./Home";
export { Admin } from "./Admin";
export { ProductList } from "./ProductList";
export { ProductDetail } from "./ProductDetail";
export { Contact } from "./Contacts/Contact";
export { ContactIN } from "./Contacts/ContactIN";
export { ContactUS } from "./Contacts/ContactUS";
export { ContactEU } from "./Contacts/ContactEU";
export { PageNotFound } from "./PageNotFound";
